%% COMPLETE ANALYISIS
% This script is used to generate the file that is loading in the image
% exporting files, therefore no visual output is provided. 

clc; clear; close all;
addpath(genpath("."))
set(0, 'DefaultFigureWindowStyle', 'docked')

% CHANGE HERE THE ARRAY
data = convert_data('config/linear_array.yml');

% Compute optimal splitting
[data.simulation.U, data.instrument.combination, ...
    data.instrument.phase_shifts] = compute_optimal_splitting(...
    data.instrument.apertures, data.instrument.baseline, ...
    data.instrument.wavelength, data.instrument.positions(:, 1), ...
    data.instrument.positions(:, 2), ...
    data.environment.stellar_angular_radius, false);

% Classify baselines
[data.instrument.baselines, data.instrument.unique_baselines] = ...
    classify_baselines(data.instrument.intensities, data.instrument.positions, data.instrument.phase_shifts, true);

% Complex Field and Response Function
[~, data] = compute_response_function("data", data);

% Verify modulation of the signal
[data.simulation.planet_modulation] = planet_modulation(data);

% Find nulling ratio
[data.simulation.nulling_ratio, data.simulation.rejection_factor] = ...
    compute_nulling_ratio(data.instrument.apertures, data.instrument.intensities, ...
    data.instrument.phase_shifts, data.instrument.positions, ...
    data.environment.stellar_angular_radius, data.instrument.wavelength);

% Point Spread Function
[data.simulation.PSF, ~, ~] = compute_psf(data.instrument.wavelength, ...
    data.instrument.intensities, data.instrument.positions, data.instrument.phase_shifts, ...
    data.environment.exoplanet_position, data.simulation.theta_range);

% Interferometer sensitivity - single arm
[data.outputs.response_function.perturbed, data.outputs.response_function.nominal, ...
 data.outputs.response_function.maps.perturbed, data.simulation.nulling_ratio_interferogram.perturbed, ...
 data.simulation.modulation_efficiency_interferogram.perturbed] = ...
    interferogram_sensitivity(data.simulation.code_v.nominal.opd, ...
    data.simulation.code_v.perturbed.opd, data.instrument.intensities,...
    data.instrument.phase_shifts, data.instrument.positions, data.instrument.combination, ...
    data.instrument.surfaces, data.instrument.wavelength);

[data.outputs.response_function.corrected, ~, data.outputs.response_function.maps.corrected, ...
    data.simulation.nulling_ratio_interferogram.corrected, ...
    data.simulation.modulation_efficiency_interferogram.corrected] = ...
    interferogram_sensitivity(data.simulation.code_v.nominal.opd, ...
    data.simulation.code_v.corrected.opd, data.instrument.intensities,...
    data.instrument.phase_shifts, data.instrument.positions, data.instrument.combination, ...
    data.instrument.surfaces, data.instrument.wavelength);

% Interferometer sensitivity - multiple arms
[data.simulation.interferogram_multi.RFp, data.simulation.interferogram_multi.RFn, ...
 data.simulation.interferogram_multi.R, data.simulation.interferogram_multi.nulling] = ...
 interferogram_sensitivity_multiple_branches(data.simulation.code_v.nominal.opd, ...
    data.simulation.code_v.corrected.opd, data.instrument.intensities,...
    data.instrument.phase_shifts, data.instrument.positions, ...
    data.instrument.combination, data.instrument.wavelength);

% PSF and Transmission maps of perturbed systems
[data.simulation.perturbation.ratio, data.simulation.perturbation.transmission_maps, ...
    data.simulation.perturbation.nominal_map, data.simulation.perturbation.PSFs, ...
    data.simulation.perturbation.nominal_PSF]  = perturbate_system(data.instrument.apertures, ...
                    data.instrument.intensities, data.instrument.phase_shifts, ...
                    data.instrument.positions, data.environment.stellar_angular_radius, ...
                    data.instrument.wavelength, data.simulation.code_v.perturbed.phase, data.instrument.combination, ...
                    perturbed_map_plotting_number=0, compute_PSF=true, create_plots=false);

% PPOP yield
data.instrument.IWA = data.instrument.wavelength / data.instrument.baseline;
data.instrument.OWA = data.instrument.wavelength / data.instrument.diameter(1);
[data.simulation.yield.ppop_table, data.simulation.yield.ppop_matrix] = get_ppop_yield(data.instrument.IWA, ...
    data.instrument.OWA, data.simulation.perturbation.ratio, data.instrument.wavelength, "create_plots", false);

clc;
save("exports/data_"+data.instrument.name+".mat", "data", "-v7.3");


%                      .
%                     / V\
%                   / `  /
%                  <<   |
%                  /    |
%                /      |
%              /        |
%            /    \  \ /
%           (      ) | |
%   ________|   _/_  | |
% <__________\______)\__)