figures:

    - type: configuration
      chapter: 2
      width: half
      height: normal

    - type: optimal_modes
      chapter: 2
      width: half
      height: normal
      include:
        modes_maps:
            width: quart
            height: quart
        modes_comparison:
            width: half
            height: normal

    - type: transmission_map
      chapter: 2
      width: half
      height: normal

    - type: transmission_map_planet
      chapter: 2
      include:
        array_plots:
            width: quart
            height: quart
      width: half
      height: normal

    - type: transmission_map_monodirectional
      include:
      - T_standard
      - T_chopped
      names:
      - Nominal
      - Chopped
      chapter: 2
      width: half
      height: normal

    - type: psf_map
      chapter: 2
      width: half
      height: normal

    - type: nullratio_single_branch_single_wavelenth
      chapter: 3
      width: half
      height: normal

    - type: nullratio_single_branch
      chapter: 3
      width: half
      height: normal

    - type: nullratio_double_branch_discrete
      wavelengths: [0.1e-6, 1e-6, 10e-6]
      chapter: 3
      width: third
      height: normal

    - type: nullratio_double_branch
      chapter: 3
      width: full
      height: normal

tables:

    - type: unique_baselines
      chapter: 2




chapters:
    - name: intro
    - name: modelling
    - name: sensitivity

sizes:
    width:
        full: 20
        half: 12
        third: 8
        quart: 5.5
    height:
        normal: 10
        quart: 5
    font_size: 10
