figures:

    - type: optimal_modes
      chapter: 2
      width: half
      height: normal
      include:
        modes_maps:
            width: quart
            height: quart
        modes_comparison:
            width: half
            height: normal

    - type: transmission_map
      chapter: 2
      width: half
      height: normal

    - type: transmission_map_planet
      chapter: 2
      width: quart
      height: quart

    - type: transmission_map_monodirectional
      include:
      - T_standard
      - T_chopped
      names:
      - Nominal
      - Chopped
      chapter: 2
      width: half
      height: normal

    - type: psf_map
      chapter: 2
      width: half
      height: normal

tables:

    - type: unique_baselines
      chapter: 2




chapters:
    - name: intro
    - name: modelling
    - name: sensitivity

sizes:
    width:
        full: 20
        half: 12
        quart: 5
    height:
        normal: 10
        quart: 4.7
    font_size: 9
