figures:

    - type: configuration
      chapter: 2
      width: half
      height: normal

    - type: optimal_modes
      chapter: 2
      width: half
      height: normal
      include:
        modes_maps:
            width: quart
            height: quart
        modes_comparison:
            width: half
            height: normal

    - type: transmission_map
      chapter: 2
      width: half
      height: normal

    - type: transmission_map_planet
      chapter: 2
      include:
        array_plots:
            width: quart
            height: quart
      width: half
      height: normal

    - type: transmission_map_monodirectional
      include:
      - T_standard
      - T_chopped
      names:
      - Nominal
      - Chopped
      chapter: 2
      width: half
      height: normal

    - type: psf_map
      chapter: 2
      width: half
      height: normal



    - type: nullratio_single_branch_single_wavelenth
      chapter: 3
      width: half
      height: normal

    - type: nullratio_single_branch
      chapter: 3
      width: half
      height: normal

    - type: nullratio_double_branch_discrete
      wavelengths: [0.1e-6, 1e-6, 10e-6]
      chapter: 3
      width: third
      height: normal

    - type: nullratio_double_branch
      chapter: 3
      width: full
      height: normal

    - type: opd_pupil_plane_system
      chapter: 3
      width: half
      height: normal

    - type: phase_pupil_plane_system
      chapter: 3
      width: half
      height: normal

    - type: sensitivity_opd_system
      include:
        - fitted_gaussian
        - rms_vs_std
      chapter: 3
      width: half
      height: normal



    # - type: interferogram
    #   maps_to_compute: 3
    #   include:
    #     interferometer_response_angles:
    #         width: third
    #         height: quart
    #     interferometer_nulling_angles:
    #         width: third
    #         height: quart
    #     interferometer_nulling_statistics:
    #         width: half
    #         height: normal
    #     interferometer_response_function:
    #         width: full
    #         height: normal
    #   chapter: 4
    #   width: third
    #   height: quart
    #
    # - type: interferogram_multiple
    #   include:
    #     interferometer_response_angles:
    #         width: third
    #         height: quart
    #     interferometer_nulling_angles:
    #         width: third
    #         height: quart
    #     interferometer_nulling_statistics:
    #         width: half
    #         height: normal
    #     interferometer_response_function:
    #         width: full
    #         height: normal
    #   chapter: 4
    #   width: third
    #   height: quart
    #
    # - type: transmission_map_perturbed
    #   include:
    #     - STD
    #     - CDF
    #     - PCA
    #     - PC1
    #   chapter: 4
    #   width: half
    #   height: normal
    #
    # - type: psf_perturbed
    #   include:
    #     - STD
    #     - CDF
    #     - PCA
    #     - PC1
    #   chapter: 4
    #   width: half
    #   height: normal

    - type: ppop_yield
      chapter: 4
      width: half
      height: normal

tables:

    # - type: unique_baselines
    #   chapter: 2




chapters:
    - name: intro
      path: /Users/francesco/Library/CloudStorage/OneDrive-Personale/Università/SEMESTRE 12/TESI/Thesis/main/
    - name: modelling
      path: /Users/francesco/Library/CloudStorage/OneDrive-Personale/Università/SEMESTRE 12/TESI/Thesis/main/
    - name: sensitivity
      path: /Users/francesco/Library/CloudStorage/OneDrive-Personale/Università/SEMESTRE 12/TESI/Thesis/main/
    - name: results
      path: /Users/francesco/Library/CloudStorage/OneDrive-Personale/Università/SEMESTRE 12/TESI/Thesis/paperino/67f92ac5d9ea1e6dd82b036e/

sizes:
    width:
        full: 20
        half: 12
        third: 8
        quart: 5.5
    height:
        normal: 10
        quart: 5
    font_size: 10
