instrument:
    apertures: 4
    baseline: 10.5
    apertures_ratio: 3
    array: Linear
    intensities:
     - [0.56, 0.56, 0.56, 0.56]
    phase_shifts:
     - [270, 180, 90, 0]
    combination:
     - [1, 1, 1, 1]

    wavelength: 10e-6

    efficiencies:
        beam_combiner: 0.25
        optical_line: 0.2

environment:

    target_distance: 10                 # [pc]
    star_radius: 696340000              # [m]
    star_temperature: 5770              # [K]

    exoplanet_radius: 6378000           # [m]
    exoplanet_position:                 # x, y in [rad]
        - [2.42407e-7, 0]

    disturbances:                       # [1]

        star_flux: 7.5e5                # Stellar flux [photons/s/m^2]
        planet_flux: 0.0775             # Planet flux [photons/s/m^2]

        effective_solid_angle: 8.75e-12 # sterad

        external_perturbations:
            intensity: 1e-2
            phase: 1e-2
            x_position: 1e-3
            y_position: 1e-3

        instrumental_leakage:
            intensity: 2e-6
            phase: 1e-5
            polarisation: 1e-5


simulation:
    consider_non_ideal: true                # If false, fields with [1] are optional
    model: external_perturbations           # [1] Model to use
    monte_carlo_iterations: 1              # [1]

    planet_modulation_positions: 0    # Number of rotations of the array to consider for the modulation

    angular_extension:
        theta_x: [-0.1e-6, 0.1e-6, 500]    # start, end, number of points
        theta_y: [-0.1e-7, 0.1e-7, 2]       # start, end, number of points


outputs:
    plot_array: true

    plot_planets: 0
    planets_angular_separations:
     - 3e-6
     - 10e-6
     - 15e-6

    plot_star: true
